// Auto-generated by decode_pkt78_netguid_map.py
// NetGUID positions inside captured pkt#78's full inner stream
// (bit offsets are relative to the START OF FIRST BUNCH, which
// is bit 122 of inner_data and matches kCapturedPkt78FullStream
// bit 0).
//
// Use these for surgical NetGUID substitution: read packed-int at
// stream_bit_offset, replace with new packed-int (recompute byte
// length), then shift subsequent bits.
//
// Total candidates found: 0

#pragma once
#include <cstdint>
#include <cstddef>

namespace aoc { namespace net {

struct CapturedPkt78NetGuid {
    std::uint32_t  stream_bit_offset;  // bit offset in kCapturedPkt78FullStream
    std::uint8_t   n_bits;             // current packed-int length in bits
    std::uint64_t  raw_value;          // (value << 1) | dynamic
    std::uint64_t  decoded_value;      // raw >> 1
    bool           is_dynamic;
    const char*    nearby_string;      // name string this GUID precedes (or null)
    const char*    inferred_role;
};

static constexpr CapturedPkt78NetGuid kCapturedPkt78NetGuids[] = {
};

static constexpr std::size_t kCapturedPkt78NetGuidCount = 0;

}}  // namespace aoc::net
