#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AoCLoginGameModeBP

#include "Basic.hpp"

#include "AoCLoginGameModeBP_classes.hpp"
#include "AoCLoginGameModeBP_parameters.hpp"


SDK_NAMESPACE_START

// Function AoCLoginGameModeBP.AoCLoginGameModeBP_C.ExecuteUbergraph_AoCLoginGameModeBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAoCLoginGameModeBP_C::ExecuteUbergraph_AoCLoginGameModeBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AoCLoginGameModeBP_C", "ExecuteUbergraph_AoCLoginGameModeBP");

	Params::AoCLoginGameModeBP_C_ExecuteUbergraph_AoCLoginGameModeBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AoCLoginGameModeBP.AoCLoginGameModeBP_C.InitializeInfiniteMonitor
// (BlueprintCallable, BlueprintEvent)

void AAoCLoginGameModeBP_C::InitializeInfiniteMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AoCLoginGameModeBP_C", "InitializeInfiniteMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AoCLoginGameModeBP.AoCLoginGameModeBP_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAoCLoginGameModeBP_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AoCLoginGameModeBP_C", "ReceiveEndPlay");

	Params::AoCLoginGameModeBP_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AoCLoginGameModeBP.AoCLoginGameModeBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAoCLoginGameModeBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AoCLoginGameModeBP_C", "ReceiveTick");

	Params::AoCLoginGameModeBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AoCLoginGameModeBP.AoCLoginGameModeBP_C.VerifyLoginInformation
// (Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    UserName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Password                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class AAoCPlayerController*             PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AAoCLoginGameModeBP_C::VerifyLoginInformation(const class FString& UserName, const class FString& Password, class AAoCPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AoCLoginGameModeBP_C", "VerifyLoginInformation");

	Params::AoCLoginGameModeBP_C_VerifyLoginInformation Parms{};

	Parms.UserName = std::move(UserName);
	Parms.Password = std::move(Password);
	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
