#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AoCSettingsManager

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass AoCSettingsManager.AoCSettingsManager_C
// 0x0000 (0x0108 - 0x0108)
class UAoCSettingsManager_C final : public UIntrepidSettingsManager
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AoCSettingsManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AoCSettingsManager_C")
	}
	static class UAoCSettingsManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAoCSettingsManager_C>();
	}
};
DUMPER7_ASSERTS_UAoCSettingsManager_C;

SDK_NAMESPACE_END
