#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: APOCConstantsBP

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass APOCConstantsBP.APOCConstantsBP_C
// 0x0000 (0x0400 - 0x0400)
class UAPOCConstantsBP_C final : public UAoCConstants
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("APOCConstantsBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"APOCConstantsBP_C")
	}
	static class UAPOCConstantsBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAPOCConstantsBP_C>();
	}
};
DUMPER7_ASSERTS_UAPOCConstantsBP_C;

SDK_NAMESPACE_END
