#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Automation

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class Automation.AutomationInputs
// 0x0000 (0x0048 - 0x0048)
class UAutomationInputs final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AutomationInputs")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AutomationInputs")
	}
	static class UAutomationInputs* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAutomationInputs>();
	}
};
DUMPER7_ASSERTS_UAutomationInputs;

// Class Automation.IntrepidAutomationSubsystem
// 0x0000 (0x0050 - 0x0050)
class UIntrepidAutomationSubsystem final : public UGameInstanceSubsystem
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("IntrepidAutomationSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IntrepidAutomationSubsystem")
	}
	static class UIntrepidAutomationSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIntrepidAutomationSubsystem>();
	}
};
DUMPER7_ASSERTS_UIntrepidAutomationSubsystem;

SDK_NAMESPACE_END
