#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Body_M_Bold

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Body_M_Bold.Body_M_Bold_C
// 0x0000 (0x01B0 - 0x01B0)
class UBody_M_Bold_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Body_M_Bold_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Body_M_Bold_C")
	}
	static class UBody_M_Bold_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBody_M_Bold_C>();
	}
};
DUMPER7_ASSERTS_UBody_M_Bold_C;

SDK_NAMESPACE_END
