#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CC_BardButton

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CC_BardButton.CC_BardButton_C
// 0x0000 (0x0780 - 0x0780)
class UCC_BardButton_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CC_BardButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CC_BardButton_C")
	}
	static class UCC_BardButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCC_BardButton_C>();
	}
};
DUMPER7_ASSERTS_UCC_BardButton_C;

SDK_NAMESPACE_END
