#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CC_FacePresetsButton

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CC_FacePresetsButton.CC_FacePresetsButton_C
// 0x0000 (0x0780 - 0x0780)
class UCC_FacePresetsButton_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CC_FacePresetsButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CC_FacePresetsButton_C")
	}
	static class UCC_FacePresetsButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCC_FacePresetsButton_C>();
	}
};
DUMPER7_ASSERTS_UCC_FacePresetsButton_C;

SDK_NAMESPACE_END
