#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterCreatorTopButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CharacterCreatorTopButtonStyle.CharacterCreatorTopButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UCharacterCreatorTopButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CharacterCreatorTopButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CharacterCreatorTopButtonStyle_C")
	}
	static class UCharacterCreatorTopButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCharacterCreatorTopButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UCharacterCreatorTopButtonStyle_C;

SDK_NAMESPACE_END
