#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConfirmButton

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ConfirmButton.ConfirmButton_C
// 0x0000 (0x0780 - 0x0780)
class UConfirmButton_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ConfirmButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ConfirmButton_C")
	}
	static class UConfirmButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfirmButton_C>();
	}
};
DUMPER7_ASSERTS_UConfirmButton_C;

SDK_NAMESPACE_END
