#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CSRectangleFadeButtonStyle_Left_Disabled

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CSRectangleFadeButtonStyle_Left_Disabled.CSRectangleFadeButtonStyle_Left_Disabled_C
// 0x0000 (0x0780 - 0x0780)
class UCSRectangleFadeButtonStyle_Left_Disabled_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CSRectangleFadeButtonStyle_Left_Disabled_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CSRectangleFadeButtonStyle_Left_Disabled_C")
	}
	static class UCSRectangleFadeButtonStyle_Left_Disabled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCSRectangleFadeButtonStyle_Left_Disabled_C>();
	}
};
DUMPER7_ASSERTS_UCSRectangleFadeButtonStyle_Left_Disabled_C;

SDK_NAMESPACE_END
