#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CTAButtonSmall_SmallCaps

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CTAButtonSmall_SmallCaps.CTAButtonSmall_SmallCaps_C
// 0x0000 (0x0780 - 0x0780)
class UCTAButtonSmall_SmallCaps_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CTAButtonSmall_SmallCaps_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CTAButtonSmall_SmallCaps_C")
	}
	static class UCTAButtonSmall_SmallCaps_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCTAButtonSmall_SmallCaps_C>();
	}
};
DUMPER7_ASSERTS_UCTAButtonSmall_SmallCaps_C;

SDK_NAMESPACE_END
