#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DenyButton

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DenyButton.DenyButton_C
// 0x0000 (0x0780 - 0x0780)
class UDenyButton_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DenyButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DenyButton_C")
	}
	static class UDenyButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDenyButton_C>();
	}
};
DUMPER7_ASSERTS_UDenyButton_C;

SDK_NAMESPACE_END
