#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DisabledButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DisabledButtonStyle.DisabledButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UDisabledButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DisabledButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DisabledButtonStyle_C")
	}
	static class UDisabledButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDisabledButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UDisabledButtonStyle_C;

SDK_NAMESPACE_END
