#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EyeButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EyeButtonStyle.EyeButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UEyeButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EyeButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EyeButtonStyle_C")
	}
	static class UEyeButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEyeButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UEyeButtonStyle_C;

SDK_NAMESPACE_END
