#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Gauntlet

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class Gauntlet.GauntletTestController
// 0x0008 (0x0050 - 0x0048)
class UGauntletTestController : public UObject
{
public:
	uint8                                         Pad_48[0x8];                                       // 0x0048(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GauntletTestController")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GauntletTestController")
	}
	static class UGauntletTestController* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGauntletTestController>();
	}
};
DUMPER7_ASSERTS_UGauntletTestController;

// Class Gauntlet.GauntletTestControllerBootTest
// 0x0000 (0x0050 - 0x0050)
class UGauntletTestControllerBootTest final : public UGauntletTestController
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GauntletTestControllerBootTest")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GauntletTestControllerBootTest")
	}
	static class UGauntletTestControllerBootTest* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGauntletTestControllerBootTest>();
	}
};
DUMPER7_ASSERTS_UGauntletTestControllerBootTest;

// Class Gauntlet.GauntletTestControllerErrorTest
// 0x0020 (0x0070 - 0x0050)
class UGauntletTestControllerErrorTest final : public UGauntletTestController
{
public:
	uint8                                         Pad_50[0x20];                                      // 0x0050(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GauntletTestControllerErrorTest")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GauntletTestControllerErrorTest")
	}
	static class UGauntletTestControllerErrorTest* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGauntletTestControllerErrorTest>();
	}
};
DUMPER7_ASSERTS_UGauntletTestControllerErrorTest;

SDK_NAMESPACE_END
