#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Header

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Header.Header_C
// 0x0000 (0x01B0 - 0x01B0)
class UHeader_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Header_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Header_C")
	}
	static class UHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeader_C>();
	}
};
DUMPER7_ASSERTS_UHeader_C;

SDK_NAMESPACE_END
