#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IntrepidEOS

#include "Basic.hpp"


SDK_NAMESPACE_START

// ScriptStruct IntrepidEOS.EOSAccountHelpers
// 0x0001 (0x0001 - 0x0000)
struct FEOSAccountHelpers final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FEOSAccountHelpers;

// ScriptStruct IntrepidEOS.EOSProductUserId
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FEOSProductUserId final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FEOSProductUserId;

SDK_NAMESPACE_END
