#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JournalStoryArcFilter

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass JournalStoryArcFilter.JournalStoryArcFilter_C
// 0x0000 (0x0780 - 0x0780)
class UJournalStoryArcFilter_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("JournalStoryArcFilter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JournalStoryArcFilter_C")
	}
	static class UJournalStoryArcFilter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJournalStoryArcFilter_C>();
	}
};
DUMPER7_ASSERTS_UJournalStoryArcFilter_C;

SDK_NAMESPACE_END
