#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ListItem_Odd

#include "Basic.hpp"

#include "StandardButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ListItem_Odd.ListItem_Odd_C
// 0x0000 (0x0780 - 0x0780)
class UListItem_Odd_C final : public UStandardButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ListItem_Odd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ListItem_Odd_C")
	}
	static class UListItem_Odd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UListItem_Odd_C>();
	}
};
DUMPER7_ASSERTS_UListItem_Odd_C;

SDK_NAMESPACE_END
