#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ListItem_Even

#include "Basic.hpp"

#include "StandardButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ListItem_Even.ListItem_Even_C
// 0x0000 (0x0780 - 0x0780)
class UListItem_Even_C final : public UStandardButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ListItem_Even_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ListItem_Even_C")
	}
	static class UListItem_Even_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UListItem_Even_C>();
	}
};
DUMPER7_ASSERTS_UListItem_Even_C;

SDK_NAMESPACE_END
