#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MinMaxToggleRoundButtonStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MinMaxToggleRoundButtonStyle.MinMaxToggleRoundButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UMinMaxToggleRoundButtonStyle_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MinMaxToggleRoundButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MinMaxToggleRoundButtonStyle_C")
	}
	static class UMinMaxToggleRoundButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMinMaxToggleRoundButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UMinMaxToggleRoundButtonStyle_C;

SDK_NAMESPACE_END
