#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ObjectiveAccordionPrimaryButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ObjectiveAccordionPrimaryButtonStyle.ObjectiveAccordionPrimaryButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UObjectiveAccordionPrimaryButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ObjectiveAccordionPrimaryButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ObjectiveAccordionPrimaryButtonStyle_C")
	}
	static class UObjectiveAccordionPrimaryButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UObjectiveAccordionPrimaryButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UObjectiveAccordionPrimaryButtonStyle_C;

SDK_NAMESPACE_END
