#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScrollRightButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ScrollRightButtonStyle.ScrollRightButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UScrollRightButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ScrollRightButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ScrollRightButtonStyle_C")
	}
	static class UScrollRightButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScrollRightButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UScrollRightButtonStyle_C;

SDK_NAMESPACE_END
