#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandardInnerContentBG

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass StandardInnerContentBG.StandardInnerContentBG_C
// 0x0000 (0x0100 - 0x0100)
class UStandardInnerContentBG_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StandardInnerContentBG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StandardInnerContentBG_C")
	}
	static class UStandardInnerContentBG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandardInnerContentBG_C>();
	}
};
DUMPER7_ASSERTS_UStandardInnerContentBG_C;

SDK_NAMESPACE_END
