#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Subheader_SanSerif

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Subheader_SanSerif.Subheader_SanSerif_C
// 0x0000 (0x01B0 - 0x01B0)
class USubheader_SanSerif_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Subheader_SanSerif_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Subheader_SanSerif_C")
	}
	static class USubheader_SanSerif_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USubheader_SanSerif_C>();
	}
};
DUMPER7_ASSERTS_USubheader_SanSerif_C;

SDK_NAMESPACE_END
