#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreateBuyOrderButton

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CreateBuyOrderButton.WBP_CreateBuyOrderButton_C
// 0x0000 (0x1730 - 0x1730)
class UWBP_CreateBuyOrderButton_C final : public UCommonTextButtonBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CreateBuyOrderButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CreateBuyOrderButton_C")
	}
	static class UWBP_CreateBuyOrderButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CreateBuyOrderButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CreateBuyOrderButton_C;

SDK_NAMESPACE_END
