#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TooltipRiderEffectsBlock

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TooltipRiderEffectsBlock.WBP_TooltipRiderEffectsBlock_C
// 0x0018 (0x0380 - 0x0368)
class UWBP_TooltipRiderEffectsBlock_C final : public UTooltipRiderEffectsBlock
{
public:
	class UWBP_TooltipEffectEntry_C*              WBP_TooltipEffectEntry_1;                          // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_TooltipEffectEntry_C*              WBP_TooltipEffectEntry;                            // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          SectionBG;                                         // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TooltipRiderEffectsBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TooltipRiderEffectsBlock_C")
	}
	static class UWBP_TooltipRiderEffectsBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TooltipRiderEffectsBlock_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TooltipRiderEffectsBlock_C;

SDK_NAMESPACE_END
