#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DamageMeterHealthLogBar

#include "Basic.hpp"

#include "WBP_DamageMeterHealthLogBar_classes.hpp"
#include "WBP_DamageMeterHealthLogBar_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DamageMeterHealthLogBar.WBP_DamageMeterHealthLogBar_C.BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DamageMeterHealthLogBar_C::BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamageMeterHealthLogBar_C", "BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DamageMeterHealthLogBar.WBP_DamageMeterHealthLogBar_C.BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DamageMeterHealthLogBar_C::BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamageMeterHealthLogBar_C", "BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DamageMeterHealthLogBar.WBP_DamageMeterHealthLogBar_C.BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DamageMeterHealthLogBar_C::BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamageMeterHealthLogBar_C", "BndEvt__DesignDamageMeter_Bar_BarButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DamageMeterHealthLogBar.WBP_DamageMeterHealthLogBar_C.ExecuteUbergraph_WBP_DamageMeterHealthLogBar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DamageMeterHealthLogBar_C::ExecuteUbergraph_WBP_DamageMeterHealthLogBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamageMeterHealthLogBar_C", "ExecuteUbergraph_WBP_DamageMeterHealthLogBar");

	Params::WBP_DamageMeterHealthLogBar_C_ExecuteUbergraph_WBP_DamageMeterHealthLogBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DamageMeterHealthLogBar.WBP_DamageMeterHealthLogBar_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_DamageMeterHealthLogBar_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamageMeterHealthLogBar_C", "OnMouseButtonDown");

	Params::WBP_DamageMeterHealthLogBar_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
