#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitFrameLayoutMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UnitFrameLayoutMenu.WBP_UnitFrameLayoutMenu_C
// 0x0020 (0x0498 - 0x0478)
class UWBP_UnitFrameLayoutMenu_C final : public UUnitFrameLayoutMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0478(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UComboBoxString*                        WidgetHierarchyDropDown;                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        ToScreensDropDown;                                 // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        AnchoredToDropDown;                                // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void DisplayUndoDebugTextBP(const TArray<struct FHudElementState>& CachedStates);
	void ExecuteUbergraph_WBP_UnitFrameLayoutMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UnitFrameLayoutMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UnitFrameLayoutMenu_C")
	}
	static class UWBP_UnitFrameLayoutMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UnitFrameLayoutMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UnitFrameLayoutMenu_C;

SDK_NAMESPACE_END
