#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GuildWarListItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GuildWarListItem.WBP_GuildWarListItem_C
// 0x0000 (0x1750 - 0x1750)
class UWBP_GuildWarListItem_C final : public UGuildWarListItem
{
public:
	class UAoCCommonButtonBase* GetButton();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GuildWarListItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GuildWarListItem_C")
	}
	static class UWBP_GuildWarListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GuildWarListItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GuildWarListItem_C;

SDK_NAMESPACE_END
