#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NotificationsGrid

#include "Basic.hpp"

#include "WBP_NotificationsGrid_classes.hpp"
#include "WBP_NotificationsGrid_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_NotificationsGrid.WBP_NotificationsGrid_C.ExecuteUbergraph_WBP_NotificationsGrid
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NotificationsGrid_C::ExecuteUbergraph_WBP_NotificationsGrid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotificationsGrid_C", "ExecuteUbergraph_WBP_NotificationsGrid");

	Params::WBP_NotificationsGrid_C_ExecuteUbergraph_WBP_NotificationsGrid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NotificationsGrid.WBP_NotificationsGrid_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NotificationsGrid_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotificationsGrid_C", "PreConstruct");

	Params::WBP_NotificationsGrid_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
