#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TimerTextBlock

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TimerTextBlock.WBP_TimerTextBlock_C
// 0x0008 (0x0458 - 0x0450)
class UWBP_TimerTextBlock_C final : public UTimerTextBlock
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ConstructSettings(class UTextBlock* Widget, bool IsVisible_0, const class FString& Text, bool HasPostfix);
	void ExecuteUbergraph_WBP_TimerTextBlock(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TimerTextBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TimerTextBlock_C")
	}
	static class UWBP_TimerTextBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TimerTextBlock_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TimerTextBlock_C;

SDK_NAMESPACE_END
