#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatTabFilter

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ChatTabFilter.WBP_ChatTabFilter_C
// 0x0010 (0x03B0 - 0x03A0)
class UWBP_ChatTabFilter_C final : public UChatTabFilter
{
public:
	class UCheckBox*                              HiddenCheckBox;                                    // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          AlternatingBG;                                     // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatTabFilter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatTabFilter_C")
	}
	static class UWBP_ChatTabFilter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatTabFilter_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatTabFilter_C;

SDK_NAMESPACE_END
