#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RelicActivationInfo

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_RelicActivationInfo.WBP_RelicActivationInfo_C
// 0x0020 (0x0410 - 0x03F0)
class UWBP_RelicActivationInfo_C final : public URelicActivationInfo
{
public:
	class UWBP_RelicInfoEntry_C*                  WBP_RelicInfoEntry_2;                              // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_RelicInfoEntry_C*                  WBP_RelicInfoEntry_1;                              // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_RelicInfoEntry_C*                  WBP_RelicInfoEntry;                                // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   InsufficientEssenceCostLabel;                      // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RelicActivationInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RelicActivationInfo_C")
	}
	static class UWBP_RelicActivationInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RelicActivationInfo_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RelicActivationInfo_C;

SDK_NAMESPACE_END
