#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerHousingListViewEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PlayerHousingListViewEntry.WBP_PlayerHousingListViewEntry_C
// 0x0000 (0x0380 - 0x0380)
class UWBP_PlayerHousingListViewEntry_C final : public UPlayerHousingListViewEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayerHousingListViewEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayerHousingListViewEntry_C")
	}
	static class UWBP_PlayerHousingListViewEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerHousingListViewEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PlayerHousingListViewEntry_C;

SDK_NAMESPACE_END
