#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CaravanLootPanel

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CaravanLootPanel.WBP_CaravanLootPanel_C
// 0x0000 (0x03B0 - 0x03B0)
class UWBP_CaravanLootPanel_C final : public UCaravanLootPanel
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CaravanLootPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CaravanLootPanel_C")
	}
	static class UWBP_CaravanLootPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CaravanLootPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CaravanLootPanel_C;

SDK_NAMESPACE_END
