#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatTextColorItem

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ChatTextColorItem.WBP_ChatTextColorItem_C
// 0x0018 (0x0380 - 0x0368)
class UWBP_ChatTextColorItem_C final : public UUserWidget
{
public:
	class UWBP_ColorPickerDropdown_C*             RightColorDropdown;                                // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ColorPickerDropdown_C*             LeftColorDropdown;                                 // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          AlternatingBG;                                     // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatTextColorItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatTextColorItem_C")
	}
	static class UWBP_ChatTextColorItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatTextColorItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatTextColorItem_C;

SDK_NAMESPACE_END
