#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SkillTree

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SkillTree.WBP_SkillTree_C
// 0x0018 (0x09D0 - 0x09B8)
class UWBP_SkillTree_C final : public USkilltree
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_SkillTreeTierWidget_C*             WBP_SkillTreeTierWidget;                           // 0x09C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUniformGridPanel*                      SkillTreeGrid;                                     // 0x09C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_SkillTree(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SkillTree_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SkillTree_C")
	}
	static class UWBP_SkillTree_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SkillTree_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SkillTree_C;

SDK_NAMESPACE_END
