#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BugReportMenu

#include "Basic.hpp"

#include "WBP_BugReportMenu_classes.hpp"
#include "WBP_BugReportMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_BugReportMenu.WBP_BugReportMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_BugReportMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BugReportMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BugReportMenu.WBP_BugReportMenu_C.ExecuteUbergraph_WBP_BugReportMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BugReportMenu_C::ExecuteUbergraph_WBP_BugReportMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BugReportMenu_C", "ExecuteUbergraph_WBP_BugReportMenu");

	Params::WBP_BugReportMenu_C_ExecuteUbergraph_WBP_BugReportMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BugReportMenu.WBP_BugReportMenu_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_BugReportMenu_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BugReportMenu_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
