#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DialogInteractionBinding

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DialogInteractionBinding.WBP_DialogInteractionBinding_C
// 0x0000 (0x03C0 - 0x03C0)
class UWBP_DialogInteractionBinding_C final : public UDialogInteractionBinding
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DialogInteractionBinding_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DialogInteractionBinding_C")
	}
	static class UWBP_DialogInteractionBinding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DialogInteractionBinding_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DialogInteractionBinding_C;

SDK_NAMESPACE_END
