#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CrateUnpackConfirmation

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CrateUnpackConfirmation.WBP_CrateUnpackConfirmation_C
// 0x0000 (0x03E8 - 0x03E8)
class UWBP_CrateUnpackConfirmation_C final : public UCrateUnpackConfirmationAlert
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CrateUnpackConfirmation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CrateUnpackConfirmation_C")
	}
	static class UWBP_CrateUnpackConfirmation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CrateUnpackConfirmation_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CrateUnpackConfirmation_C;

SDK_NAMESPACE_END
