#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServiceBuildingStatWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ServiceBuildingStatWidget.WBP_ServiceBuildingStatWidget_C
// 0x0020 (0x0388 - 0x0368)
class UWBP_ServiceBuildingStatWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAoCCommonTextBlock*                    ValueTextBlock;                                    // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAoCCommonTextBlock*                    LabelTextBlock;                                    // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          B_MainContainer;                                   // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ServiceBuildingStatWidget(int32 EntryPoint);
	class UCommonBorder* GetBorder();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ServiceBuildingStatWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ServiceBuildingStatWidget_C")
	}
	static class UWBP_ServiceBuildingStatWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ServiceBuildingStatWidget_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ServiceBuildingStatWidget_C;

SDK_NAMESPACE_END
