#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FriendsListItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FriendsListItem.WBP_FriendsListItem_C
// 0x0008 (0x0430 - 0x0428)
class UWBP_FriendsListItem_C final : public UFriendsListItem
{
public:
	class UCommonButton_C*                        FriendsItemButton;                                 // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UAoCCommonButtonBase* GetButton();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FriendsListItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FriendsListItem_C")
	}
	static class UWBP_FriendsListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FriendsListItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FriendsListItem_C;

SDK_NAMESPACE_END
