#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommissionRewardsSummary

#include "Basic.hpp"

#include "WBP_CommissionRewardsSummary_classes.hpp"
#include "WBP_CommissionRewardsSummary_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CommissionRewardsSummary.WBP_CommissionRewardsSummary_C.ExecuteUbergraph_WBP_CommissionRewardsSummary
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CommissionRewardsSummary_C::ExecuteUbergraph_WBP_CommissionRewardsSummary(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CommissionRewardsSummary_C", "ExecuteUbergraph_WBP_CommissionRewardsSummary");

	Params::WBP_CommissionRewardsSummary_C_ExecuteUbergraph_WBP_CommissionRewardsSummary Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CommissionRewardsSummary.WBP_CommissionRewardsSummary_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CommissionRewardsSummary_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CommissionRewardsSummary_C", "PreConstruct");

	Params::WBP_CommissionRewardsSummary_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
