#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServiceBuildingMaintenanceItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ServiceBuildingMaintenanceItem.WBP_ServiceBuildingMaintenanceItem_C
// 0x0010 (0x0478 - 0x0468)
class UWBP_ServiceBuildingMaintenanceItem_C final : public UServiceBuildingMaintenanceItem
{
public:
	class UCommonBorder*                          BuildingIconBorder;                                // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          AlternatingBG;                                     // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ServiceBuildingMaintenanceItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ServiceBuildingMaintenanceItem_C")
	}
	static class UWBP_ServiceBuildingMaintenanceItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ServiceBuildingMaintenanceItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ServiceBuildingMaintenanceItem_C;

SDK_NAMESPACE_END
