#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NameplateColorRow

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NameplateColorRow.WBP_NameplateColorRow_C
// 0x0008 (0x0470 - 0x0468)
class UWBP_NameplateColorRow_C final : public UNameplateColorRow
{
public:
	class UCommonBorder*                          AlternatingBG;                                     // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NameplateColorRow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NameplateColorRow_C")
	}
	static class UWBP_NameplateColorRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NameplateColorRow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NameplateColorRow_C;

SDK_NAMESPACE_END
