#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionsMenuLabeledSubsection

#include "Basic.hpp"

#include "WBP_LabeledWrapBox_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_OptionsMenuLabeledSubsection.WBP_OptionsMenuLabeledSubsection_C
// 0x0000 (0x03F8 - 0x03F8)
class UWBP_OptionsMenuLabeledSubsection_C final : public UWBP_LabeledWrapBox_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_OptionsMenuLabeledSubsection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_OptionsMenuLabeledSubsection_C")
	}
	static class UWBP_OptionsMenuLabeledSubsection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OptionsMenuLabeledSubsection_C>();
	}
};
DUMPER7_ASSERTS_UWBP_OptionsMenuLabeledSubsection_C;

SDK_NAMESPACE_END
