#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuildingManagerSection

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BuildingManagerSection.WBP_BuildingManagerSection_C
// 0x0010 (0x03E8 - 0x03D8)
class UWBP_BuildingManagerSection_C final : public UBuildingManagerSection
{
public:
	class UNamedSlot*                             NamedSlot;                                         // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIntrepidVerticalBox*                   ItemsBox;                                          // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BuildingManagerSection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BuildingManagerSection_C")
	}
	static class UWBP_BuildingManagerSection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BuildingManagerSection_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BuildingManagerSection_C;

SDK_NAMESPACE_END
