#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TooltipCoreStatEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TooltipCoreStatEntry.WBP_TooltipCoreStatEntry_C
// 0x0000 (0x0388 - 0x0388)
class UWBP_TooltipCoreStatEntry_C final : public UTooltipCoreStatEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TooltipCoreStatEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TooltipCoreStatEntry_C")
	}
	static class UWBP_TooltipCoreStatEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TooltipCoreStatEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TooltipCoreStatEntry_C;

SDK_NAMESPACE_END
