#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NodeRelationshipSummary

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NodeRelationshipSummary.WBP_NodeRelationshipSummary_C
// 0x0020 (0x04D8 - 0x04B8)
class UWBP_NodeRelationshipSummary_C final : public UNodeRelationshipsSummary
{
public:
	class UWBP_CurrentWarHistoryItem_C*           WBP_CurrentWarHistoryItem_2;                       // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CurrentWarHistoryItem_C*           WBP_CurrentWarHistoryItem_1;                       // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CurrentWarHistoryItem_C*           WBP_CurrentWarHistoryItem;                         // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAoCCommonTextBlock*                    TB_HistorySectionLabel;                            // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NodeRelationshipSummary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NodeRelationshipSummary_C")
	}
	static class UWBP_NodeRelationshipSummary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NodeRelationshipSummary_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NodeRelationshipSummary_C;

SDK_NAMESPACE_END
