#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TooltipBase

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TooltipBase.WBP_TooltipBase_C
// 0x0010 (0x03F8 - 0x03E8)
class UWBP_TooltipBase_C final : public UTooltipBase
{
public:
	class UImage*                                 InnerFrame;                                        // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       TooltipFadeIn;                                     // 0x03F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TooltipBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TooltipBase_C")
	}
	static class UWBP_TooltipBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TooltipBase_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TooltipBase_C;

SDK_NAMESPACE_END
