#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SkillPoint

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SkillPoint.WBP_SkillPoint_C
// 0x0000 (0x03D8 - 0x03D8)
class UWBP_SkillPoint_C final : public USkillPoint
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SkillPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SkillPoint_C")
	}
	static class UWBP_SkillPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SkillPoint_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SkillPoint_C;

SDK_NAMESPACE_END
