#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommissionDifficultyIcon

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CommissionDifficultyIcon.WBP_CommissionDifficultyIcon_C
// 0x0010 (0x0428 - 0x0418)
class UWBP_CommissionDifficultyIcon_C final : public UCommissionDifficultyIcon
{
public:
	class UImage*                                 IMG_DifficultyFrame;                               // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               CommissionDifficultyContainer;                     // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CommissionDifficultyIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CommissionDifficultyIcon_C")
	}
	static class UWBP_CommissionDifficultyIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommissionDifficultyIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CommissionDifficultyIcon_C;

SDK_NAMESPACE_END
