#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommodityTooltip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CommodityTooltip.WBP_CommodityTooltip_C
// 0x0018 (0x04C8 - 0x04B0)
class UWBP_CommodityTooltip_C final : public UCommodityTooltip
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonBorder*                          SectionBG;                                         // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   RMBMessage;                                        // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CommodityTooltip(int32 EntryPoint);
	class UCommonBorder* GetBorder();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CommodityTooltip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CommodityTooltip_C")
	}
	static class UWBP_CommodityTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommodityTooltip_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CommodityTooltip_C;

SDK_NAMESPACE_END
