#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RewardsSummary_Small

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_RewardsSummary_Small.WBP_RewardsSummary_Small_C
// 0x0008 (0x04C0 - 0x04B8)
class UWBP_RewardsSummary_Small_C final : public URewardSummary
{
public:
	class UImage*                                 xpIcon;                                            // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RewardsSummary_Small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RewardsSummary_Small_C")
	}
	static class UWBP_RewardsSummary_Small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RewardsSummary_Small_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RewardsSummary_Small_C;

SDK_NAMESPACE_END
