#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SiegeParticipantListEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SiegeParticipantListEntry.WBP_SiegeParticipantListEntry_C
// 0x0010 (0x0508 - 0x04F8)
class UWBP_SiegeParticipantListEntry_C final : public USiegeParticipantListEntry
{
public:
	class UAoCCommonTextBlock*                    StatusTextBlock;                                   // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          B_AlternatingBG;                                   // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SiegeParticipantListEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SiegeParticipantListEntry_C")
	}
	static class UWBP_SiegeParticipantListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SiegeParticipantListEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SiegeParticipantListEntry_C;

SDK_NAMESPACE_END
