#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatTabCategory

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ChatTabCategory.WBP_ChatTabCategory_C
// 0x0000 (0x0398 - 0x0398)
class UWBP_ChatTabCategory_C final : public UChatTabCategory
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatTabCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatTabCategory_C")
	}
	static class UWBP_ChatTabCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatTabCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatTabCategory_C;

SDK_NAMESPACE_END
