#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EventRadiusPOIW

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_EventRadiusPOIW.WBP_EventRadiusPOIW_C
// 0x0008 (0x0D78 - 0x0D70)
class UWBP_EventRadiusPOIW_C final : public UMapEventPOIW
{
public:
	class UBorder*                                MainBorder;                                        // 0x0D70(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EventRadiusPOIW_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EventRadiusPOIW_C")
	}
	static class UWBP_EventRadiusPOIW_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EventRadiusPOIW_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EventRadiusPOIW_C;

SDK_NAMESPACE_END
