#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemStolenOverlay

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ItemStolenOverlay.WBP_ItemStolenOverlay_C
// 0x0010 (0x0378 - 0x0368)
class UWBP_ItemStolenOverlay_C final : public UUserWidget
{
public:
	class UOverlay*                               StolenOverlay;                                     // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox;                                           // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ItemStolenOverlay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ItemStolenOverlay_C")
	}
	static class UWBP_ItemStolenOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ItemStolenOverlay_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ItemStolenOverlay_C;

SDK_NAMESPACE_END
