#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WindowFrame_ReviveModal

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_WindowFrame_ReviveModal.WBP_WindowFrame_ReviveModal_C
// 0x0010 (0x0818 - 0x0808)
class UWBP_WindowFrame_ReviveModal_C final : public UAoCWindow
{
public:
	class UCommonXButton_C*                       DeathSummaryButton;                                // 0x0808(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       WindowOpenClose;                                   // 0x0810(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_WindowFrame_ReviveModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_WindowFrame_ReviveModal_C")
	}
	static class UWBP_WindowFrame_ReviveModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WindowFrame_ReviveModal_C>();
	}
};
DUMPER7_ASSERTS_UWBP_WindowFrame_ReviveModal_C;

SDK_NAMESPACE_END
