#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DeleteRankModal

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DeleteRankModal.WBP_DeleteRankModal_C
// 0x0000 (0x03E8 - 0x03E8)
class UWBP_DeleteRankModal_C final : public UDeleteRankModal
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DeleteRankModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DeleteRankModal_C")
	}
	static class UWBP_DeleteRankModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DeleteRankModal_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DeleteRankModal_C;

SDK_NAMESPACE_END
