#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextTooltipIcon

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TextTooltipIcon.WBP_TextTooltipIcon_C
// 0x0000 (0x03C0 - 0x03C0)
class UWBP_TextTooltipIcon_C final : public UTextTooltipIcon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TextTooltipIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TextTooltipIcon_C")
	}
	static class UWBP_TextTooltipIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TextTooltipIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TextTooltipIcon_C;

SDK_NAMESPACE_END
