#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DestiniesSkillTreeNode

#include "Basic.hpp"

#include "WBP_DestiniesSkillTreeNode_classes.hpp"
#include "WBP_DestiniesSkillTreeNode_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DestiniesSkillTreeNode.WBP_DestiniesSkillTreeNode_C.ExecuteUbergraph_WBP_DestiniesSkillTreeNode
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DestiniesSkillTreeNode_C::ExecuteUbergraph_WBP_DestiniesSkillTreeNode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DestiniesSkillTreeNode_C", "ExecuteUbergraph_WBP_DestiniesSkillTreeNode");

	Params::WBP_DestiniesSkillTreeNode_C_ExecuteUbergraph_WBP_DestiniesSkillTreeNode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DestiniesSkillTreeNode.WBP_DestiniesSkillTreeNode_C.SetRadialSliderProgressBP
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DestiniesSkillTreeNode_C::SetRadialSliderProgressBP(float Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DestiniesSkillTreeNode_C", "SetRadialSliderProgressBP");

	Params::WBP_DestiniesSkillTreeNode_C_SetRadialSliderProgressBP Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
