#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ColorPickerDropdown_OptionsMenu

#include "Basic.hpp"

#include "WBP_ColorPickerDropdown_OptionsMenu_classes.hpp"
#include "WBP_ColorPickerDropdown_OptionsMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ColorPickerDropdown_OptionsMenu.WBP_ColorPickerDropdown_OptionsMenu_C.GetBorder
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonBorder*                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UCommonBorder* UWBP_ColorPickerDropdown_OptionsMenu_C::GetBorder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ColorPickerDropdown_OptionsMenu_C", "GetBorder");

	Params::WBP_ColorPickerDropdown_OptionsMenu_C_GetBorder Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
