#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WindowFTUE

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_WindowFTUE.WBP_WindowFTUE_C
// 0x0020 (0x0488 - 0x0468)
class UWBP_WindowFTUE_C final : public UWindowFTUE
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0468(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCheckBox*                              HideHintsCheckbox;                                 // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       ModalOpenClose;                                    // 0x0478(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ArrowIdle;                                         // 0x0480(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_WindowFTUE(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_WindowFTUE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_WindowFTUE_C")
	}
	static class UWBP_WindowFTUE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WindowFTUE_C>();
	}
};
DUMPER7_ASSERTS_UWBP_WindowFTUE_C;

SDK_NAMESPACE_END
