#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuyOrderFulfillmentMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BuyOrderFulfillmentMenu.WBP_BuyOrderFulfillmentMenu_C
// 0x0010 (0x0700 - 0x06F0)
class UWBP_BuyOrderFulfillmentMenu_C final : public UBuyOrderFulfillmentMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_ContextualModal_C*                 FulfillmentSummaryModal;                           // 0x06F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BuyOrderFulfillmentMenu(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BuyOrderFulfillmentMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BuyOrderFulfillmentMenu_C")
	}
	static class UWBP_BuyOrderFulfillmentMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BuyOrderFulfillmentMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BuyOrderFulfillmentMenu_C;

SDK_NAMESPACE_END
