#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RaidOptionsMenu

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_RaidOptionsMenu.WBP_RaidOptionsMenu_C
// 0x0008 (0x0438 - 0x0430)
class UWBP_RaidOptionsMenu_C final : public URaidOptionsMenu
{
public:
	class UCheckBox*                              CheckBox_EnableVoice_1;                            // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RaidOptionsMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RaidOptionsMenu_C")
	}
	static class UWBP_RaidOptionsMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RaidOptionsMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RaidOptionsMenu_C;

SDK_NAMESPACE_END
