#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CitizenshipWindow

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CitizenshipWindow.WBP_CitizenshipWindow_C
// 0x0010 (0x0620 - 0x0610)
class UWBP_CitizenshipWindow_C final : public UCitizenshipWindow
{
public:
	class UCommonTextBlock*                       SubPanelIndicatorTextBlock;                        // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScrollWindow_NoFrameNoPadding_C*   ScW_Content;                                       // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CitizenshipWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CitizenshipWindow_C")
	}
	static class UWBP_CitizenshipWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CitizenshipWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CitizenshipWindow_C;

SDK_NAMESPACE_END
