#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MaintenanceResourceItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MaintenanceResourceItem.WBP_MaintenanceResourceItem_C
// 0x0010 (0x0430 - 0x0420)
class UWBP_MaintenanceResourceItem_C final : public UMaintenanceResourceItem
{
public:
	class UAoCCommonTextBlock*                    CommodityTierTextBlock;                            // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          AlternatingBG;                                     // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MaintenanceResourceItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MaintenanceResourceItem_C")
	}
	static class UWBP_MaintenanceResourceItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MaintenanceResourceItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MaintenanceResourceItem_C;

SDK_NAMESPACE_END
