#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuyOrderFulfillmentMenu

#include "Basic.hpp"

#include "WBP_BuyOrderFulfillmentMenu_classes.hpp"
#include "WBP_BuyOrderFulfillmentMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_BuyOrderFulfillmentMenu.WBP_BuyOrderFulfillmentMenu_C.ExecuteUbergraph_WBP_BuyOrderFulfillmentMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BuyOrderFulfillmentMenu_C::ExecuteUbergraph_WBP_BuyOrderFulfillmentMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BuyOrderFulfillmentMenu_C", "ExecuteUbergraph_WBP_BuyOrderFulfillmentMenu");

	Params::WBP_BuyOrderFulfillmentMenu_C_ExecuteUbergraph_WBP_BuyOrderFulfillmentMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BuyOrderFulfillmentMenu.WBP_BuyOrderFulfillmentMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BuyOrderFulfillmentMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BuyOrderFulfillmentMenu_C", "PreConstruct");

	Params::WBP_BuyOrderFulfillmentMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
