#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tab

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Tab.WBP_Tab_C
// 0x0000 (0x1740 - 0x1740)
class UWBP_Tab_C final : public UCommonTab
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Tab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Tab_C")
	}
	static class UWBP_Tab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Tab_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Tab_C;

SDK_NAMESPACE_END
