#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MayoralCommissionDeliveryItem

#include "Basic.hpp"

#include "WBP_MayoralCommissionDeliveryItem_classes.hpp"
#include "WBP_MayoralCommissionDeliveryItem_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MayoralCommissionDeliveryItem.WBP_MayoralCommissionDeliveryItem_C.ExecuteUbergraph_WBP_MayoralCommissionDeliveryItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MayoralCommissionDeliveryItem_C::ExecuteUbergraph_WBP_MayoralCommissionDeliveryItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MayoralCommissionDeliveryItem_C", "ExecuteUbergraph_WBP_MayoralCommissionDeliveryItem");

	Params::WBP_MayoralCommissionDeliveryItem_C_ExecuteUbergraph_WBP_MayoralCommissionDeliveryItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MayoralCommissionDeliveryItem.WBP_MayoralCommissionDeliveryItem_C.GetBorderContainer
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPanelWidget*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UPanelWidget* UWBP_MayoralCommissionDeliveryItem_C::GetBorderContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MayoralCommissionDeliveryItem_C", "GetBorderContainer");

	Params::WBP_MayoralCommissionDeliveryItem_C_GetBorderContainer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MayoralCommissionDeliveryItem.WBP_MayoralCommissionDeliveryItem_C.GetEvenBorderStyle
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonBorderStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonBorderStyle> UWBP_MayoralCommissionDeliveryItem_C::GetEvenBorderStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MayoralCommissionDeliveryItem_C", "GetEvenBorderStyle");

	Params::WBP_MayoralCommissionDeliveryItem_C_GetEvenBorderStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MayoralCommissionDeliveryItem.WBP_MayoralCommissionDeliveryItem_C.GetOddBorderStyle
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonBorderStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonBorderStyle> UWBP_MayoralCommissionDeliveryItem_C::GetOddBorderStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MayoralCommissionDeliveryItem_C", "GetOddBorderStyle");

	Params::WBP_MayoralCommissionDeliveryItem_C_GetOddBorderStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MayoralCommissionDeliveryItem.WBP_MayoralCommissionDeliveryItem_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MayoralCommissionDeliveryItem_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MayoralCommissionDeliveryItem_C", "PreConstruct");

	Params::WBP_MayoralCommissionDeliveryItem_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
