#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GemSlot

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GemSlot.WBP_GemSlot_C
// 0x0000 (0x04D8 - 0x04D8)
class UWBP_GemSlot_C final : public UGemSlot
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GemSlot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GemSlot_C")
	}
	static class UWBP_GemSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GemSlot_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GemSlot_C;

SDK_NAMESPACE_END
