#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SearchableSurveying

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SearchableSurveying.WBP_SearchableSurveying_C
// 0x0008 (0x04F0 - 0x04E8)
class UWBP_SearchableSurveying_C final : public USearchableSurveying
{
public:
	class UAoCCommonTextBlock*                    AvailableResourcesText;                            // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SearchableSurveying_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SearchableSurveying_C")
	}
	static class UWBP_SearchableSurveying_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SearchableSurveying_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SearchableSurveying_C;

SDK_NAMESPACE_END
