#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CC_PortalWidgetItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CC_PortalWidgetItem.WBP_CC_PortalWidgetItem_C
// 0x0010 (0x03E8 - 0x03D8)
class UWBP_CC_PortalWidgetItem_C final : public UCCPortalWidgetItem
{
public:
	class UCommonBorder*                          SubcategoryBG;                                     // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SelectedImg;                                       // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CC_PortalWidgetItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CC_PortalWidgetItem_C")
	}
	static class UWBP_CC_PortalWidgetItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CC_PortalWidgetItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CC_PortalWidgetItem_C;

SDK_NAMESPACE_END
