#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NotificationsViewAll

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NotificationsViewAll.WBP_NotificationsViewAll_C
// 0x0010 (0x03B0 - 0x03A0)
class UWBP_NotificationsViewAll_C final : public UNotificationsViewAll
{
public:
	class UCommonTextBlock*                       SubPanelIndicatorTextBlock;                        // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScrollWindow_NoFrameNoPadding_C*   NotifcationsScrollingList;                         // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NotificationsViewAll_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NotificationsViewAll_C")
	}
	static class UWBP_NotificationsViewAll_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NotificationsViewAll_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NotificationsViewAll_C;

SDK_NAMESPACE_END
