#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RadarRadiusPOIW

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_RadarRadiusPOIW.WBP_RadarRadiusPOIW_C
// 0x0008 (0x07C8 - 0x07C0)
class UWBP_RadarRadiusPOIW_C final : public UPOIW
{
public:
	class UBorder*                                MainBorder;                                        // 0x07C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RadarRadiusPOIW_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RadarRadiusPOIW_C")
	}
	static class UWBP_RadarRadiusPOIW_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RadarRadiusPOIW_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RadarRadiusPOIW_C;

SDK_NAMESPACE_END
