#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DialogueChoiceItem

#include "Basic.hpp"

#include "WBP_DialogueChoiceItem_classes.hpp"
#include "WBP_DialogueChoiceItem_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DialogueChoiceItem.WBP_DialogueChoiceItem_C.GetButton
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAoCCommonButtonBase*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UAoCCommonButtonBase* UWBP_DialogueChoiceItem_C::GetButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueChoiceItem_C", "GetButton");

	Params::WBP_DialogueChoiceItem_C_GetButton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
