#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ZoneOverlayPOIW

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ZoneOverlayPOIW.WBP_ZoneOverlayPOIW_C
// 0x0008 (0x0CC8 - 0x0CC0)
class UWBP_ZoneOverlayPOIW_C final : public UZoneOverlayPOIW
{
public:
	class UBorder*                                MainBorder;                                        // 0x0CC0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ZoneOverlayPOIW_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ZoneOverlayPOIW_C")
	}
	static class UWBP_ZoneOverlayPOIW_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ZoneOverlayPOIW_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ZoneOverlayPOIW_C;

SDK_NAMESPACE_END
