#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MailItem

#include "Basic.hpp"

#include "WBP_MailItem_classes.hpp"
#include "WBP_MailItem_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MailItem.WBP_MailItem_C.GetButton
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAoCCommonButtonBase*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UAoCCommonButtonBase* UWBP_MailItem_C::GetButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MailItem_C", "GetButton");

	Params::WBP_MailItem_C_GetButton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MailItem.WBP_MailItem_C.GetButtonContainer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPanelWidget*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UPanelWidget* UWBP_MailItem_C::GetButtonContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MailItem_C", "GetButtonContainer");

	Params::WBP_MailItem_C_GetButtonContainer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MailItem.WBP_MailItem_C.GetEvenButtonStyle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonButtonStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonButtonStyle> UWBP_MailItem_C::GetEvenButtonStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MailItem_C", "GetEvenButtonStyle");

	Params::WBP_MailItem_C_GetEvenButtonStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MailItem.WBP_MailItem_C.GetOddButtonStyle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonButtonStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonButtonStyle> UWBP_MailItem_C::GetOddButtonStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MailItem_C", "GetOddButtonStyle");

	Params::WBP_MailItem_C_GetOddButtonStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
