#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TooltipRequirementSection

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TooltipRequirementSection.WBP_TooltipRequirementSection_C
// 0x0008 (0x0390 - 0x0388)
class UWBP_TooltipRequirementSection_C final : public UTooltipRequirementSection
{
public:
	class UCommonBorder*                          AlternatingBG;                                     // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();
	class UPanelWidget* GetBorderContainer();
	TSubclassOf<class UCommonBorderStyle> GetEvenBorderStyle();
	TSubclassOf<class UCommonBorderStyle> GetOddBorderStyle();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TooltipRequirementSection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TooltipRequirementSection_C")
	}
	static class UWBP_TooltipRequirementSection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TooltipRequirementSection_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TooltipRequirementSection_C;

SDK_NAMESPACE_END
