#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ActiveSiegeItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ActiveSiegeItem.WBP_ActiveSiegeItem_C
// 0x0000 (0x0380 - 0x0380)
class UWBP_ActiveSiegeItem_C final : public UActiveSiegeItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ActiveSiegeItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ActiveSiegeItem_C")
	}
	static class UWBP_ActiveSiegeItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ActiveSiegeItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ActiveSiegeItem_C;

SDK_NAMESPACE_END
