#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NodeBuildingListItem

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NodeBuildingListItem.WBP_NodeBuildingListItem_C
// 0x0020 (0x18D0 - 0x18B0)
class UWBP_NodeBuildingListItem_C final : public UNodeBuildingListItem
{
public:
	class UImage*                                 TimerProgressBarFrame;                             // 0x18B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ConstructionProgressBarTextBlock;                  // 0x18B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          B_BuildingListItem;                                // 0x18C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UAoCCommonButtonBase* GetButton();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NodeBuildingListItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NodeBuildingListItem_C")
	}
	static class UWBP_NodeBuildingListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NodeBuildingListItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NodeBuildingListItem_C;

SDK_NAMESPACE_END
