#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GuildRankListEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GuildRankListEntry.WBP_GuildRankListEntry_C
// 0x0008 (0x0388 - 0x0380)
class UWBP_GuildRankListEntry_C final : public UGuildRankListEntry
{
public:
	class UCommonBorder*                          B_GradientBG;                                      // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GuildRankListEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GuildRankListEntry_C")
	}
	static class UWBP_GuildRankListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GuildRankListEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GuildRankListEntry_C;

SDK_NAMESPACE_END
