#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowBG_Loot

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WindowBG_Loot.WindowBG_Loot_C
// 0x0000 (0x0100 - 0x0100)
class UWindowBG_Loot_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WindowBG_Loot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WindowBG_Loot_C")
	}
	static class UWindowBG_Loot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowBG_Loot_C>();
	}
};
DUMPER7_ASSERTS_UWindowBG_Loot_C;

SDK_NAMESPACE_END
