#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowFrameLrg_Standard_960px

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WindowFrameLrg_Standard_960px.WindowFrameLrg_Standard_960px_C
// 0x0000 (0x0100 - 0x0100)
class UWindowFrameLrg_Standard_960px_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WindowFrameLrg_Standard_960px_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WindowFrameLrg_Standard_960px_C")
	}
	static class UWindowFrameLrg_Standard_960px_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowFrameLrg_Standard_960px_C>();
	}
};
DUMPER7_ASSERTS_UWindowFrameLrg_Standard_960px_C;

SDK_NAMESPACE_END
