#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowFrame_Loot

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WindowFrame_Loot.WindowFrame_Loot_C
// 0x0000 (0x0100 - 0x0100)
class UWindowFrame_Loot_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WindowFrame_Loot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WindowFrame_Loot_C")
	}
	static class UWindowFrame_Loot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowFrame_Loot_C>();
	}
};
DUMPER7_ASSERTS_UWindowFrame_Loot_C;

SDK_NAMESPACE_END
