#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowFrame_Simple

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WindowFrame_Simple.WindowFrame_Simple_C
// 0x0000 (0x0100 - 0x0100)
class UWindowFrame_Simple_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WindowFrame_Simple_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WindowFrame_Simple_C")
	}
	static class UWindowFrame_Simple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowFrame_Simple_C>();
	}
};
DUMPER7_ASSERTS_UWindowFrame_Simple_C;

SDK_NAMESPACE_END
