#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XButtonStyle

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass XButtonStyle.XButtonStyle_C
// 0x0000 (0x0780 - 0x0780)
class UXButtonStyle_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("XButtonStyle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"XButtonStyle_C")
	}
	static class UXButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UXButtonStyle_C>();
	}
};
DUMPER7_ASSERTS_UXButtonStyle_C;

SDK_NAMESPACE_END
