#!/usr/bin/env python3
"""
PM42 (2026-04-30) — Extract the player Pawn ActorOpen bunch stream from
replay_data.bin at packet index 89 (seq=14354 in the captured session).

Verbose UE5 net log (with launch_all.bat) confirmed packet 89 contains the
player's PlayerPawn_C ActorOpen on ch=19:

  "Received: Channel[19]. Seq 954. PacketId: 14354"
  "InternalLoadObject loaded PlayerPawn_C
     /Game/ThirdPersonCPP/Blueprints/PlayerPawn.Default__PlayerPawn_C
     from NetGUID <ObjectId: 9327572450991073355 | ServerId: 0 | Randomizer: 0>"
  "SerializeNewActor END: Actor: PlayerPawn_C_2147477215, Channel: 19,
     [ObjectId: 10341538 | ServerId: 60 | Randomizer: 1860730596]"

Subsequent packets 14355..14358 carry the partial-bunch continuation with
the 8 subobjects (BaseCharacterInfo / CombatInfo / OwnerInfo /
BackpackComponent / EquipmentComponent / QuestStorageComponent /
RewardStorageComponent / Character Appearance) — but they're NOT in pkt 89,
they're in pkts 90..93 inclusive.

This script extracts pkt 89's bunch bits ONLY (the channel-open header +
SerializeNewActor body for the actor itself).  Subobject content lives in
the continuation packets which we may want to splice separately or natively
generate later.

Output:
  - captured_player_pawn_bunches_raw.bin
  - captured_player_pawn_bunches_raw.h
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.stdout.reconfigure(encoding='utf-8')

# Use existing replay reader
candidates = [
    HERE / '..' / '..' / '..' / 'dist' / 'Release' / 'archive' / 're_scripts',
    HERE,
]
for c in candidates:
    sys.path.insert(0, str(c))
from decode_pc_precise import read_replay

DIST_RELEASE = HERE / '..' / '..' / '..' / 'dist' / 'Release'
REPLAY_BIN = DIST_RELEASE / 'replay_data.bin'

OUT_BIN = HERE / 'captured_player_pawn_bunches_raw.bin'
OUT_HDR = HERE / 'captured_player_pawn_bunches_raw.h'

PKT_IDX = 89  # = seq 14354 - initSeq 14265 (player Pawn ActorOpen on ch=19)

print(f"Reading {REPLAY_BIN} ...")
packets = read_replay(str(REPLAY_BIN))
if PKT_IDX >= len(packets):
    print(f"ERROR: pkt index {PKT_IDX} out of range (only {len(packets)})")
    sys.exit(1)

p = packets[PKT_IDX]
raw = p['raw']
bsb = p['bsb']
bb  = p['bb']
seq = p.get('seq', '?')
print(f"  pkt[{PKT_IDX}]: bytes={len(raw)} bsb={bsb} bb={bb} seq={seq}")

# Extract bunch bits from RAW bit position bsb for bb bits
total_bits = bb
total_bytes = (total_bits + 7) // 8
out_bytes = bytearray(total_bytes)
out_bit = 0
for src_bit in range(bsb, bsb + total_bits):
    bit = (raw[src_bit >> 3] >> (src_bit & 7)) & 1
    if bit:
        out_bytes[out_bit >> 3] |= (1 << (out_bit & 7))
    out_bit += 1
assert out_bit == total_bits

OUT_BIN.write_bytes(out_bytes)
print(f"Wrote {OUT_BIN} ({len(out_bytes)} bytes, {total_bits} bits)")

# Emit C++ header
with OUT_HDR.open('w', encoding='utf-8') as f:
    f.write("// Auto-generated by extract_player_pawn_pkt89.py\n")
    f.write(f"// Source: replay_data.bin pkt[{PKT_IDX}] bits [{bsb}..{bsb+bb})\n")
    f.write("// Player Pawn ActorOpen (Default__PlayerPawn_C on ch=19).\n")
    f.write("// Captured archetype/level/instance NetGUIDs need to be patched\n")
    f.write("// by the runtime emitter to use OUR session's minted NetGUIDs.\n")
    f.write(f"// Total: {total_bits} bits ({total_bytes} bytes)\n\n")
    f.write("#pragma once\n#include <cstdint>\n#include <cstddef>\n\n")
    f.write("namespace aoc { namespace net {\n\n")
    f.write("static constexpr std::uint8_t kCapturedPlayerPawnBunchStream[] = {\n")
    for i in range(0, len(out_bytes), 8):
        chunk = out_bytes[i:i+8]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        f.write(f"    {hex_bytes},\n")
    f.write("};\n\n")
    f.write(f"static constexpr std::size_t kCapturedPlayerPawnBunchStreamBits  = {total_bits};\n")
    f.write(f"static constexpr std::size_t kCapturedPlayerPawnBunchStreamBytes = {total_bytes};\n\n")
    f.write("}} // namespace aoc::net\n")
print(f"Wrote {OUT_HDR}")
