#!/usr/bin/env python3
"""extract_pkt78_full_stream.py - extract the FULL pkt#78 inner stream
(all 3 bunches concatenated bit-exactly) and emit a C++ header for the
PlayerPawnSplicer.

Output structure of the extracted bit stream:
  - Begins at first bunch header bit (bit 149 of inner_data)
  - Concatenates: bunch[0] header+payload, bunch[1] header+payload, bunch[2] header+payload
  - Bunch boundaries flow back-to-back since each bunch's data_end aligns
    exactly with the next bunch's start.
  - Total bits = inner_total - first_bunch_start

The captured Pawn NetGUID is 54 (small legacy packed-int).  We don't
substitute it here -- the splicer ships verbatim and the client either
accepts the captured NetGUIDs as a parallel actor (if no collision with
our session) or treats them as PackageMap registrations alongside our
synthetic Pawn.
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.stdout.reconfigure(encoding='utf-8')

import phase1_parser as P

src = HERE / "captured_pkt_78.bin"
data = src.read_bytes()
parsed = P.parse_packet(data, 'S>C')
inner = parsed['inner_data']
inner_bits = len(inner) * 8

# Find the first bunch's start bit.  parse_packet returns bunches with
# 'data_start' = payload start.  Header starts before that.  The first
# bunch's header starts at the position parse_packet's outer header parser
# left off.  We compute it from the first bunch info:
b0 = parsed['bunches'][0]
first_payload = b0['data_start']
first_hdr_bits = b0.get('hdr_bits', 0)
first_bunch_start = first_payload - first_hdr_bits

# Compute total bits to extract (start of first bunch through end of
# last bunch).
b_last = parsed['bunches'][-1]
last_end = b_last['data_start'] + b_last['bunch_data_bits']
total_bits = last_end - first_bunch_start

print(f"Source: {src.name}")
print(f"  size: {len(data)} bytes / {len(data)*8} bits")
print(f"  inner: {len(inner)} bytes / {inner_bits} bits")
print(f"  first bunch start: bit {first_bunch_start}")
print(f"  last bunch end:    bit {last_end}")
print(f"  total stream bits: {total_bits} ({(total_bits + 7) // 8} bytes)")

# Extract those bits as a byte-aligned stream
stream = P.extract_realigned(inner, first_bunch_start, total_bits)

print(f"  extracted: {len(stream)} bytes")
print()
print("Bunches:")
for i, b in enumerate(parsed['bunches']):
    print(f"  [{i}] ch={b['ch']} ChSeq={b['ch_seq']} bdb={b['bunch_data_bits']} "
          f"open={b['open']} ctrl={b['ctrl']} reliable={b['reliable']} "
          f"hdr_bits={b.get('hdr_bits')} data_start={b['data_start']}")

# Generate C++ header
out_path = HERE.parent.parent / "net" / "captured_pkt78_full_stream.h"
print(f"\nGenerating: {out_path}")

with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
    f.write("// Auto-generated by extract_pkt78_full_stream.py\n")
    f.write(f"// Source: captured_pkt_78.bin (full stream)\n")
    f.write(f"//\n")
    f.write(f"// Contains the full inner-data bunch stream of pkt#78 ({len(parsed['bunches'])} bunches):\n")
    for i, b in enumerate(parsed['bunches']):
        f.write(f"//   [{i}] ch={b['ch']} ChSeq={b['ch_seq']} bdb={b['bunch_data_bits']} "
                f"open={b['open']} ctrl={b['ctrl']} reliable={b['reliable']} "
                f"hdr_bits={b.get('hdr_bits')}\n")
    f.write(f"// Total: {total_bits} bits ({len(stream)} bytes)\n")
    f.write(f"//\n")
    f.write(f"// Extraction details:\n")
    f.write(f"//   first_bunch_start_bit = {first_bunch_start}\n")
    f.write(f"//   last_bunch_end_bit    = {last_end}\n")
    f.write(f"//   stream_total_bits     = {total_bits}\n")
    f.write(f"//\n")
    f.write(f"// PlayerPawn ActorOpen subobjects discovered in bunch[2] (rel bit offsets):\n")
    f.write(f"//   bit  651: 'BaseCharacterInfo'\n")
    f.write(f"//   bit 1131: 'CombatInfo'\n")
    f.write(f"//   bit 1555: 'OwnerInfo'\n")
    f.write(f"//   bit 1971: 'BackpackComponent'\n")
    f.write(f"//   bit 2451: 'EquipmentComponent'\n")
    f.write(f"//   (3 more not visible in SIP scan: QuestStorageComponent,\n")
    f.write(f"//    RewardStorageComponent, CharacterAppearanceComponent)\n")
    f.write(f"//\n")
    f.write(f"// PlayerPawn archetype + class (from bunch[0] NetGUID exports):\n")
    f.write(f"//   bit 481 (rel): '/Game/ThirdPersonCPP/Blueprints/PlayerPawn'\n")
    f.write(f"//   bit 889 (rel): 'Default__PlayerPawn_C'\n")
    f.write(f"\n")
    f.write(f"#pragma once\n")
    f.write(f"#include <cstddef>\n")
    f.write(f"#include <cstdint>\n")
    f.write(f"\n")
    f.write(f"namespace aoc {{ namespace net {{\n")
    f.write(f"\n")
    f.write(f"static constexpr std::uint8_t kCapturedPkt78FullStream[] = {{\n")
    line = "    "
    for i, byte in enumerate(stream):
        line += f"0x{byte:02x},"
        if (i + 1) % 12 == 0:
            f.write(line + "\n")
            line = "    "
        else:
            line += " "
    if line.strip():
        f.write(line.rstrip() + "\n")
    f.write(f"}};\n")
    f.write(f"\n")
    f.write(f"static constexpr std::size_t kCapturedPkt78FullStreamBits  = {total_bits};\n")
    f.write(f"static constexpr std::size_t kCapturedPkt78FullStreamBytes = {len(stream)};\n")
    f.write(f"\n")
    f.write(f"// Per-bunch boundaries (bit offsets WITHIN this stream):\n")
    cursor = 0
    for i, b in enumerate(parsed['bunches']):
        f.write(f"static constexpr std::size_t kCapturedPkt78Bunch{i}_StartBit = {cursor};\n")
        cursor_after = cursor + b.get('hdr_bits', 0) + b['bunch_data_bits']
        f.write(f"static constexpr std::size_t kCapturedPkt78Bunch{i}_EndBit   = {cursor_after};\n")
        f.write(f"static constexpr std::size_t kCapturedPkt78Bunch{i}_HdrBits  = {b.get('hdr_bits', 0)};\n")
        f.write(f"static constexpr std::size_t kCapturedPkt78Bunch{i}_PayloadBits = {b['bunch_data_bits']};\n")
        cursor = cursor_after
    f.write(f"\n")
    f.write(f"}}}}  // namespace aoc::net\n")

print(f"  wrote {len(stream)} bytes / {total_bits} bits to header")
