#!/usr/bin/env python3
"""
extract_pc_tail.py
==================

Extract the 106 captured trailing bytes that our PC ActorOpen is missing.
These contain the initial property values + subobject content blocks
that explain why our properties never apply.

Saves:
  captured_pc_tail_bytes.bin  — raw bytes (will be embedded as a header)
  captured_pc_tail.h          — C++ header for use in actor_builder
"""
from __future__ import annotations
import sys, struct
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

from phase1_parser import parse_packet
from walk_replay_props import load_packets, REPLAY
from reassemble_and_extract_appearance import reassemble_partials

OUR_BUNCH = Path(r'<REPO_ROOT>\dist\Release\our_pc_bunch.bin')


def main():
    # Load OUR generated bunch (includes 6-byte bunch header)
    with open(OUR_BUNCH, 'rb') as f:
        ours = f.read()
    print(f'Our PC ActorOpen (with header): {len(ours)} bytes')

    # Reassemble captured
    packets = load_packets(REPLAY)
    pkt = packets[22]
    parsed = parse_packet(pkt['raw'], 'S>C')
    captured, captured_bits = reassemble_partials(parsed,
        [parsed['bunches'][0], parsed['bunches'][1]])
    print(f'Captured PC ActorOpen (BunchData only): {len(captured)} bytes')

    # Our content (skip 6-byte bunch header) = 502 bytes
    our_content = ours[6:]
    our_bits_in_content = len(our_content) * 8

    # The captured tail starts at our_content's length
    tail_start = len(our_content)
    tail = captured[tail_start:]
    tail_bits = captured_bits - our_bits_in_content
    print(f'\nMissing tail:')
    print(f'  start offset in captured: {tail_start} bytes')
    print(f'  size: {len(tail)} bytes / {tail_bits} bits')
    print(f'  hex: {tail.hex()}')

    # Save raw bytes
    out_bin = HERE / 'captured_pc_tail_bytes.bin'
    with open(out_bin, 'wb') as f:
        f.write(tail)
    print(f'\nSaved raw to {out_bin}')

    # Generate C++ header for use in actor_builder
    src_dir = Path(r'<REPO_ROOT>\src\net')
    out_h = src_dir / 'captured_pc_actoropen_tail.h'
    with open(out_h, 'w', encoding='utf-8') as f:
        f.write(f'// AUTOGENERATED by extract_pc_tail.py — DO NOT EDIT\n')
        f.write(f'//\n')
        f.write(f'// Captured AOC server\'s PC ActorOpen "tail" — the {len(tail)} bytes\n')
        f.write(f'// that follow OUR generated PC ActorOpen content.  These contain the\n')
        f.write(f'// initial property values + subobject content blocks that the captured\n')
        f.write(f'// server replicated as part of its PC ActorOpen.  Without these, our\n')
        f.write(f'// PC has empty initial state and properties never apply (PlayerState,\n')
        f.write(f'// LoadedCharacterData, etc. all stay default).\n')
        f.write(f'//\n')
        f.write(f'// Source: replay_data.bin pkt#22 reassembled bunches[0]+[1], offset {tail_start}\n')
        f.write(f'// Total content: {captured_bits} bits ({len(captured)} bytes)\n')
        f.write(f'// Our content:   {our_bits_in_content} bits ({len(our_content)} bytes)\n')
        f.write(f'// Tail size:     {tail_bits} bits ({len(tail)} bytes) ← this header\n')
        f.write(f'\n')
        f.write(f'#pragma once\n')
        f.write(f'#include <cstdint>\n')
        f.write(f'#include <cstddef>\n')
        f.write(f'\n')
        f.write(f'static constexpr std::size_t kCapturedPcTailBits  = {tail_bits};\n')
        f.write(f'static constexpr std::size_t kCapturedPcTailBytes = {len(tail)};\n')
        f.write(f'\n')
        f.write(f'static constexpr std::uint8_t kCapturedPcTail[{len(tail)}] = {{\n')
        for i in range(0, len(tail), 16):
            chunk = tail[i:i+16]
            line = '    ' + ', '.join(f'0x{b:02x}' for b in chunk)
            if i + 16 < len(tail):
                line += ','
            f.write(line + '\n')
        f.write(f'}};\n')

    print(f'Saved C++ header to {out_h}')


if __name__ == '__main__':
    main()
