#!/usr/bin/env python3
"""
Extract the raw bunch-stream bits from captured_pkt_78.bin.

pkt#78 contains 3 bunches (ch=85 GUIDExport, ch=0 data, ch=114 Pawn ActorOpen).
We want all three as a single concatenated bit stream ready to be re-wrapped
with our own packet header and shipped via IGameServerHost::send_bunch_packet.

This mirrors the approach used for `kCapturedPcTailBits` in pc_emitter.cpp —
we splice known-good captured bytes until we can emit them natively.

Output:
  - captured_pkt78_bunches_raw.bin  (binary fixture for runtime)
  - captured_pkt78_bunches_raw.h    (C++ constexpr header for embed)
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.stdout.reconfigure(encoding='utf-8')

from phase1_parser import parse_packet

FIXTURE = HERE / 'captured_pkt_78.bin'
OUT_BIN = HERE / 'captured_pkt78_bunches_raw.bin'
OUT_HDR = HERE / 'captured_pkt78_bunches_raw.h'

p = FIXTURE.read_bytes()
parsed = parse_packet(p, 'S>C')
assert parsed, "parse_packet failed"

bunches = parsed['bunches']
print(f"pkt#78: {len(bunches)} bunches, seq={parsed.get('seq')}")

# Each bunch has a header (before data_start) + its data (bdb bits).
# For re-emission we need: [bunch0 header][bunch0 data][bunch1 header][bunch1 data][bunch2 header][bunch2 data]
#
# phase1_parser tracks data_start (bit where bdb begins) + bdb length.
# The bunch's HEADER starts at `data_start - <header bit count>`.  We don't
# have the explicit header-start bit in the parser output, so we compute it
# as the previous bunch's "end" (data_start + bdb), or for bunch[0] the
# packet-header end (usually bit ~162 for a hasPacketInfo=1 data packet).

# Bunch 0 start = end of packet prefix + PacketInfo.  Inspect parser trace for bit 0 of first bunch.
# Conservative: bunch0 start = bunches[0].get('bunch_start') if present, else data_start of bunch[0]
#                                minus an estimated header size.
# Actually phase1_parser stores data_start; for re-emission we need the HEADER too.
# Solution: take bit range [bunches[0]_hdr_start .. bunches[-1].data_start + bunches[-1].bdb].
# We approximate bunches[0]_hdr_start as the "packet payload start" (after PacketInfo).

# pkt#78 uses hasPacketInfo=1, no srv frame, so PacketInfo = 162 bits offset typically.
# But bunches[0].data_start=149 per decode_pkt78_v2 output — that's where the DATA of
# bunch 0 starts, not the bunch header.  Header for bunch 0 is at 149 minus ~22 bits
# for a non-control simple bunch = ~127.
# Easier: we include everything from a known-good offset forward and LET THE CLIENT
# PARSE THE FLAGS — the raw bit stream is self-describing.

# Approach: start at the first bunch's HEADER.  phase1_parser seems to expose
# 'bunch_start' or we can derive it from the parser's internal state.  Let's
# just use bit 53 onwards — that's typically past the SC prefix + seq/ack/ackCount
# block but before PacketInfo.  Then include PacketInfo... no wait, PacketInfo is
# part of the packet header.  We should NOT include it.

# Final approach: walk the parser's bits, find where bunch 0's header begins.
# Since we don't have that directly, use the known `start_bit` for pkt#78.
# From bunches_bootstrap.log (for 29010-packet replay): pkt#78 start_bit=162, bunch_bits=119
# BUT the captured_pkt_78.bin is a DIFFERENT packet (extracted as "Pawn fixture").
# From decode_pkt78_v2: bunch[0].data_start = 149.
# So packet prefix + PacketInfo end at 149 - <bunch 0 header>.  For a non-reliable
# simple bunch header = ~22 bits (bControl, bPaused, bReliable, chIdx+SIP, bHasPkgExp,
# bHasMustMap, bPartial, chSeq 10-bit, ch_name 8-bit, bdb 13-bit, ...).
# For our pkt#78 bunch 0 (ch=85, has_exports=1, has_must_map=1), header ≈ 40-50 bits.

# Let's just try start_bit = 127 (a reasonable guess) and adjust:
FIRST_BUNCH_HEADER_BIT = 127   # EMPIRICAL — adjust after first runtime test if client NAKs

# End = data_start + bdb of last bunch
last_b = bunches[-1]
END_BIT = last_b['data_start'] + last_b['bunch_data_bits']

print(f"Extracting bits [{FIRST_BUNCH_HEADER_BIT}..{END_BIT}) = {END_BIT - FIRST_BUNCH_HEADER_BIT} bits "
      f"({(END_BIT - FIRST_BUNCH_HEADER_BIT + 7) // 8} bytes)")

# Extract bits LSB-first (same format as BunchWriter)
total_bits = END_BIT - FIRST_BUNCH_HEADER_BIT
out_bytes = bytearray((total_bits + 7) // 8)
for i in range(total_bits):
    src_bit = FIRST_BUNCH_HEADER_BIT + i
    bit = (p[src_bit >> 3] >> (src_bit & 7)) & 1
    if bit:
        out_bytes[i >> 3] |= (1 << (i & 7))

OUT_BIN.write_bytes(out_bytes)
print(f"Wrote {OUT_BIN} ({len(out_bytes)} bytes)")

# Emit C++ header
with OUT_HDR.open('w', encoding='utf-8') as f:
    f.write("// Auto-generated by extract_pkt78_bunches_raw.py\n")
    f.write(f"// Source: captured_pkt_78.bin bits [{FIRST_BUNCH_HEADER_BIT}..{END_BIT})\n")
    f.write(f"// Contains {len(bunches)} bunches:\n")
    for i, b in enumerate(bunches):
        f.write(f"//   [{i}] ch={b['ch']} ctrl={b['ctrl']} open={b.get('open',0)} "
                f"reliable={b.get('reliable',0)} bdb={b['bunch_data_bits']}\n")
    f.write(f"// Total: {total_bits} bits ({len(out_bytes)} bytes)\n\n")
    f.write("#pragma once\n#include <cstdint>\n#include <cstddef>\n\n")
    f.write("namespace aoc { namespace net {\n\n")
    f.write("static constexpr std::uint8_t kCapturedPkt78BunchStream[] = {\n")
    for i in range(0, len(out_bytes), 8):
        chunk = out_bytes[i:i+8]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        f.write(f"    {hex_bytes},\n")
    f.write("};\n\n")
    f.write(f"static constexpr std::size_t kCapturedPkt78BunchStreamBits = {total_bits};\n")
    f.write(f"static constexpr std::size_t kCapturedPkt78BunchStreamBytes = {len(out_bytes)};\n\n")
    f.write("}} // namespace aoc::net\n")

print(f"Wrote {OUT_HDR}")
