#!/usr/bin/env python3
"""
PM43 (2026-04-30) — Extract the FULL player Pawn ActorOpen partial bunch
chain from replay_data.bin: pkts 89-93 (5 packets, seq=14354..14358).

Verbose log from launch_all.bat (which played the chain successfully)
confirmed:

  PacketId 14354 → ch=19 Seq 954  ← first chunk (bPartial=1, bPartialInitial=1)
  PacketId 14355 → ch=19 Seq 955
  PacketId 14356 → ch=19 Seq 956
  PacketId 14357 → ch=19 Seq 957
  PacketId 14358 → ch=19 Seq 958  ← final chunk (bPartial=1, bPartialFinal=1)
  SerializeNewActor END (Channel 19, Default__PlayerPawn_C)

Sending only the first chunk (PM42) = "Bunch data overflowed (5939/2708)"
because the bunch declares 5939 total bits but only the first 2584 are in
pkt 89.  The client correctly buffered/dropped the partial.

PM43 ships ALL 5 chunks via 5 consecutive send_bunch_packet calls.

Output:
  - captured_player_pawn_chain.bin    (concatenated for inspection)
  - captured_player_pawn_chain.h      (5 arrays + 5 sizes)
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.stdout.reconfigure(encoding='utf-8')

candidates = [
    HERE / '..' / '..' / '..' / 'dist' / 'Release' / 'archive' / 're_scripts',
    HERE,
]
for c in candidates:
    sys.path.insert(0, str(c))
from decode_pc_precise import read_replay

DIST_RELEASE = HERE / '..' / '..' / '..' / 'dist' / 'Release'
REPLAY_BIN = DIST_RELEASE / 'replay_data.bin'

OUT_HDR = HERE / 'captured_player_pawn_chain.h'

# Captured player Pawn ActorOpen partial bunch chain
# (5 packets, all on ch=19, chSeq 954-958)
PKT_INDICES = [89, 90, 91, 92, 93]

print(f"Reading {REPLAY_BIN} ...")
packets = read_replay(str(REPLAY_BIN))

extracted = []
for idx in PKT_INDICES:
    if idx >= len(packets):
        print(f"ERROR: pkt index {idx} out of range")
        sys.exit(1)
    p = packets[idx]
    raw = p['raw']
    bsb = p['bsb']
    bb  = p['bb']
    seq = p.get('seq', '?')

    # Extract bunch bits
    total_bits = bb
    total_bytes = (total_bits + 7) // 8
    out_bytes = bytearray(total_bytes)
    out_bit = 0
    for src_bit in range(bsb, bsb + total_bits):
        bit = (raw[src_bit >> 3] >> (src_bit & 7)) & 1
        if bit:
            out_bytes[out_bit >> 3] |= (1 << (out_bit & 7))
        out_bit += 1
    assert out_bit == total_bits

    extracted.append({
        'idx': idx,
        'seq': seq,
        'raw_size': len(raw),
        'bsb': bsb,
        'bb': total_bits,
        'bytes': bytes(out_bytes),
    })
    print(f"  pkt[{idx}] seq={seq}: raw={len(raw)}B bsb={bsb} bb={total_bits} → {total_bytes} bunch bytes")

# Emit C++ header with 5 arrays + sizes
with OUT_HDR.open('w', encoding='utf-8') as f:
    f.write("// Auto-generated by extract_player_pawn_chain.py\n")
    f.write("// Source: replay_data.bin pkts[89..93] (player Pawn ActorOpen chain)\n")
    f.write("// All bunches on ch=19 with chSeq 954-958.  Together they form the\n")
    f.write("// complete SerializeNewActor body for Default__PlayerPawn_C\n")
    f.write("// (~5939 total bits across all 5 partial bunches).\n\n")
    f.write("#pragma once\n#include <cstdint>\n#include <cstddef>\n\n")
    f.write("namespace aoc { namespace net {\n\n")
    f.write(f"static constexpr size_t kPlayerPawnChainPacketCount = {len(extracted)};\n\n")

    for i, e in enumerate(extracted):
        f.write(f"// pkt[{e['idx']}] seq={e['seq']} ({e['bb']} bits / {len(e['bytes'])} bytes)\n")
        f.write(f"static constexpr std::uint8_t kPlayerPawnChunk{i}[] = {{\n")
        for j in range(0, len(e['bytes']), 8):
            chunk = e['bytes'][j:j+8]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f"    {hex_bytes},\n")
        f.write("};\n")
        f.write(f"static constexpr std::size_t kPlayerPawnChunk{i}Bits = {e['bb']};\n\n")

    # Convenience aggregator
    f.write("// Helper accessor — index 0..kPlayerPawnChainPacketCount-1.\n")
    f.write("inline const std::uint8_t* PlayerPawnChunkData(size_t i) {\n")
    for i in range(len(extracted)):
        f.write(f"    if (i == {i}) return kPlayerPawnChunk{i};\n")
    f.write("    return nullptr;\n")
    f.write("}\n\n")
    f.write("inline std::size_t PlayerPawnChunkBits(size_t i) {\n")
    for i in range(len(extracted)):
        f.write(f"    if (i == {i}) return kPlayerPawnChunk{i}Bits;\n")
    f.write("    return 0;\n")
    f.write("}\n\n")
    f.write("}} // namespace aoc::net\n")

total_bits = sum(e['bb'] for e in extracted)
total_bytes = sum(len(e['bytes']) for e in extracted)
print(f"Wrote {OUT_HDR}")
print(f"  Total: {total_bits} bits across {len(extracted)} packets ({total_bytes} bytes)")
